apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_ENV: "production"
  APP_PORT: "8080"
  DB_HOST: "mysql-service"

# # ---
# # #Method-1 : We can choose entire Config map as environment varible

# apiVersion: v1
# kind: Pod
# metadata:
#   name: app-pod
# spec:
#   containers:
#     - name: app
#       image: busybox
#       command: ["sh", "-c", "echo $APP_ENV && sleep 3600"]
#       envFrom:
#         - configMapRef:
#             name: app-config

# # ---
# #Method-2 : We can choose specifi key as Environment variable
# apiVersion: v1
# kind: Pod
# metadata:
#   name: app-pod
# spec:
#   containers:
#     - name: app
#       image: busybox
#       command: ["sh", "-c", "echo $ENVIRONMENT && sleep 3600"]
#       env:
#         - name: ENVIRONMENT
#           valueFrom:
#             configMapKeyRef:
#               name: app-config
#               key: APP_ENV

# # ---
# #method-3 : We cna mount entire config map as a mounted file. 
# apiVersion: v1
# kind: Pod
# metadata:
#   name: web-pod
# spec:
#   containers:
#     - name: nginx
#       image: nginx
#       volumeMounts:
#         - name: config-volume
#           mountPath: /etc/config
#   volumes:
#     - name: config-volume
#       configMap:
#         name: app-config